# Generated by Django 5.2.13 on 2026-04-30 19:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0002_serviceorderhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("service", "Serviço"), ("part", "Peça")],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Preço unitário",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="service_orders.serviceorder",
                        verbose_name="Ordem de serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da ordem de serviço",
                "verbose_name_plural": "Itens da ordem de serviço",
                "ordering": ["created_at"],
            },
        ),
    ]
