# Generated by Django 5.2.13 on 2026-04-30 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0003_serviceorderitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="assigned_mechanic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_service_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mecânico responsável",
            ),
        ),
        migrations.CreateModel(
            name="ServiceOrderNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("internal", "Interna"),
                            ("customer", "Cliente"),
                            ("technical", "Técnica"),
                            ("urgent", "Urgente"),
                        ],
                        default="internal",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("text", models.TextField(verbose_name="Observação")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizada em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_order_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="service_orders.serviceorder",
                        verbose_name="Ordem de serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota interna da ordem de serviço",
                "verbose_name_plural": "Notas internas das ordens de serviço",
                "ordering": ["-created_at"],
            },
        ),
    ]
