# Generated by Django 5.2.13 on 2026-05-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0004_serviceorder_assigned_mechanic_serviceordernote"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="priority",
            field=models.CharField(
                choices=[("low", "Baixa"), ("medium", "Média"), ("high", "Alta")],
                default="medium",
                max_length=20,
                verbose_name="Prioridade",
            ),
        ),
    ]
