# Generated by Django 5.2.13 on 2026-05-01 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0005_serviceorder_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrderTimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="Iniciado em")),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Encerrado em"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "mechanic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_order_time_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mecânico",
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="service_orders.serviceorder",
                        verbose_name="Ordem de serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apontamento de tempo da OS",
                "verbose_name_plural": "Apontamentos de tempo das OS",
                "ordering": ["-started_at"],
            },
        ),
    ]
