# Generated by Django 5.2.13 on 2026-05-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="auditoria_a_action_892235_idx",
            old_name="auditoria_a_action_844d0a_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="auditoria_a_app_lab_7a8767_idx",
            old_name="auditoria_a_app_lab_441fdb_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="auditoria_a_user_id_861297_idx",
            old_name="auditoria_a_user_id_e60460_idx",
        ),
    ]
