[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = --nomigrations --cov=core --cov=auditoria --cov=accounts --cov=customers --cov=service_orders --cov=inventory --cov=financial --cov=mensagens --cov-report=html
filterwarnings =
    ignore::django.utils.deprecation.RemovedInDjango60Warning

norecursedirs = .git .venv venv env htmlcov static media __pycache__
