[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = --nomigrations --cov=core --cov=accounts --cov=customers --cov=service_orders --cov=inventory --cov=financial --cov-report=html