# Generated by Django 5.2.13 on 2026-05-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em'),
        ),
    ]
