# Generated by Django 5.2.13 on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mensagens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=80, unique=True, verbose_name="Código"),
                ),
                (
                    "label",
                    models.CharField(max_length=120, verbose_name="Nome exibido"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "category",
                    models.CharField(
                        default="Geral", max_length=80, verbose_name="Categoria"
                    ),
                ),
                (
                    "example_value",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="Exemplo"
                    ),
                ),
                (
                    "source_path",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: customer.name, service_order.number ou invoice.total_amount.",
                        max_length=180,
                        verbose_name="Origem técnica",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(default=False, verbose_name="Dado sensível"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizada em"),
                ),
            ],
            options={
                "verbose_name": "Variável de mensagem",
                "verbose_name_plural": "Variáveis de mensagem",
                "ordering": ["category", "code"],
            },
        ),
        migrations.AddIndex(
            model_name="messagevariable",
            index=models.Index(
                fields=["category", "is_active"], name="mensagens_m_categor_4b878c_idx"
            ),
        ),
        migrations.RenameIndex(
            model_name="messagelog",
            new_name="mensagens_m_custome_5f7957_idx",
            old_name="mensagens_m_custome_642622_idx",
        ),
        migrations.RenameIndex(
            model_name="messagelog",
            new_name="mensagens_m_status_e6f78b_idx",
            old_name="mensagens_m_status_546a15_idx",
        ),
        migrations.RenameIndex(
            model_name="messagequeue",
            new_name="mensagens_m_status_5f23a9_idx",
            old_name="mensagens_m_status_3dce64_idx",
        ),
        migrations.RenameIndex(
            model_name="messagequeue",
            new_name="mensagens_m_custome_20c145_idx",
            old_name="mensagens_m_custome_31df55_idx",
        ),
        migrations.RenameIndex(
            model_name="messagetemplate",
            new_name="mensagens_m_code_abacab_idx",
            old_name="mensagens_m_code_3651d8_idx",
        ),
    ]
