# Generated by Django 5.2.13 on 2026-05-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mensagens", "0002_messagevariable_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="messagevariable",
            new_name="mensagens_m_categor_5f1f56_idx",
            old_name="mensagens_m_categor_4b878c_idx",
        ),
    ]
