# Generated by Django 5.2.13 on 2026-05-03 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cashflowentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("expense__isnull", True), ("payment__isnull", False)),
                    models.Q(("expense__isnull", False), ("payment__isnull", True)),
                    _connector="OR",
                ),
                name="cash_flow_has_exactly_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashflowentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("entry_type", "income"), _negated=True),
                    models.Q(("expense__isnull", True), ("payment__isnull", False)),
                    _connector="OR",
                ),
                name="cash_flow_income_requires_payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashflowentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("entry_type", "expense"), _negated=True),
                    models.Q(("expense__isnull", False), ("payment__isnull", True)),
                    _connector="OR",
                ),
                name="cash_flow_expense_requires_expense",
            ),
        ),
    ]
