# Generated by Django 5.2.13 on 2026-05-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0002_cashflowentry_cash_flow_has_exactly_one_source_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashflowentry",
            options={},
        ),
    ]
