# Generated by Django 5.2.13 on 2026-05-05 22:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do combo')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código interno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto do combo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Combo de serviços',
                'verbose_name_plural': 'Combos de serviços',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do serviço')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código interno')),
                ('category', models.CharField(blank=True, max_length=80, null=True, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço padrão')),
                ('estimated_minutes', models.PositiveIntegerField(default=0, verbose_name='Tempo estimado em minutos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço unitário no combo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workshop_services.servicecombo', verbose_name='Combo')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combo_items', to='workshop_services.workshopservice', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Item do combo',
                'verbose_name_plural': 'Itens do combo',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('combo', 'service'), name='unique_service_per_combo')],
            },
        ),
    ]
