# Generated by Django 5.2.13 on 2026-05-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_services", "0002_workshopservicepart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopservicepart",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Excluído em"
            ),
        ),
    ]
