# Generated by Django 5.2.13 on 2026-05-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_services", "0003_alter_workshopservicepart_deleted_at"),
        ("workshop_services", "0003_service_categories"),
    ]

    operations = []
