# Generated by Django 5.2.13 on 2026-05-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_services", "0004_catalog_intelligence"),
        ("workshop_services", "0004_merge_20260506_1149"),
    ]

    operations = []
