# Generated by Django 5.2.13 on 2026-05-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_services", "0005_merge_20260506_1207"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workshopservicecategory",
            options={
                "ordering": ["parent__name", "name"],
                "verbose_name": "Categoria de serviço",
                "verbose_name_plural": "Categorias de serviços",
            },
        ),
        migrations.AlterField(
            model_name="workshopservice",
            name="estimated_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Tempo operacional padrão usado em agenda, previsão e produtividade.",
                verbose_name="Tempo estimado em minutos",
            ),
        ),
    ]
