# Generated by Django 5.2.13 on 2026-05-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_serviceorderpart_service_order_item"),
        ("inventory", "0004_partbrand_partcategory_refactor"),
    ]

    operations = []
