# Generated by Django 5.2.13 on 2026-05-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_merge_20260506_1108"),
        ("inventory", "0005_service_order_part_item_link"),
    ]

    operations = []
