# Generated by Django 5.2.13 on 2026-05-06 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_merge_20260506_1207"),
        ("service_orders", "0009_serviceorder_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderpart",
            name="service_order_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Serviço específico da OS que originou esta peça.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_parts",
                to="service_orders.serviceorderitem",
                verbose_name="Serviço da OS",
            ),
        ),
    ]
