# Generated by Django 5.2.13 on 2026-05-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_purchase_order_shortage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Excluído em"
            ),
        ),
    ]
