# Generated by Django 6.0.4 on 2026-04-30 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Informe um telefone válido.",
                                regex="^[0-9+\\-\\s()]+$",
                            )
                        ],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        blank=True,
                        help_text="CPF, CNPJ, NIF ou outro documento fiscal.",
                        max_length=30,
                        null=True,
                        verbose_name="Documento",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Endereço"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate",
                    models.CharField(max_length=20, verbose_name="Matrícula/Placa"),
                ),
                ("brand", models.CharField(max_length=80, verbose_name="Marca")),
                ("model", models.CharField(max_length=80, verbose_name="Modelo")),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ano"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Cor"
                    ),
                ),
                (
                    "chassis_number",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name="Número do chassi",
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Quilometragem"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="customers.customer",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "ordering": ["plate"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plate",), name="unique_vehicle_plate"
                    )
                ],
            },
        ),
    ]
