# Generated by Django 5.2.13 on 2026-05-03 19:25

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="document",
            field=models.CharField(
                blank=True,
                help_text="CPF, CNPJ, NIF ou outro documento fiscal.",
                max_length=30,
                null=True,
                validators=[core.validators.validate_document],
                verbose_name="Documento",
            ),
        ),
    ]
