# Generated by Django 5.2.13 on 2026-05-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_city_customer_complement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Excluído em"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Excluído em"
            ),
        ),
    ]
