# Generated by Django 5.2.13 on 2026-05-04 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customerinteraction",
            new_name="crm_custome_custome_592043_idx",
            old_name="crm_custome_custome_74f7ca_idx",
        ),
        migrations.RenameIndex(
            model_name="customerinteraction",
            new_name="crm_custome_service_0de1cc_idx",
            old_name="crm_custome_service_0a6c95_idx",
        ),
        migrations.RenameIndex(
            model_name="customerinteraction",
            new_name="crm_custome_next_fo_74a640_idx",
            old_name="crm_custome_next_fo_2d885e_idx",
        ),
        migrations.RenameIndex(
            model_name="customerreminder",
            new_name="crm_custome_status_6ce5cb_idx",
            old_name="crm_custome_status_dcfbd4_idx",
        ),
        migrations.AlterField(
            model_name="customerinteraction",
            name="interaction_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data da interação"
            ),
        ),
    ]
