from django.urls import path

from .views import (
    ajax_views,
    board_views,
    calendar_views,
    item_views,
    note_views,
    order_views,
    reports_views,
    time_tracking_views,
)

app_name = "service_orders"


urlpatterns = [
    path(
        "ordens/",
        order_views.service_order_list_view,
        name="service_order_list",
    ),
    path(
        "quadro/",
        board_views.service_order_board_view,
        name="service_order_board",
    ),
    path(
        "agenda/",
        calendar_views.workshop_agenda_view,
        name="workshop_agenda",
    ),
    path(
        "relatorios/produtividade-mecanicos/",
        reports_views.mechanic_productivity_report_view,
        name="mechanic_productivity_report",
    ),
    path(
        "ordens/criar/",
        order_views.service_order_create_view,
        name="service_order_create",
    ),
    path(
        "ordens/<int:pk>/",
        order_views.service_order_detail_view,
        name="service_order_detail",
    ),
    path(
        "ordens/<int:pk>/editar/",
        order_views.service_order_update_view,
        name="service_order_update",
    ),
    path(
        "ordens/<int:pk>/tecnico/",
        order_views.service_order_technical_update_view,
        name="service_order_technical_update",
    ),
    path(
        "ordens/<int:pk>/status-rapido/",
        board_views.service_order_quick_status_update_view,
        name="service_order_quick_status_update",
    ),
    path(
        "ordens/<int:pk>/tempo/iniciar/",
        time_tracking_views.service_order_time_start_view,
        name="service_order_time_start",
    ),
    path(
        "ordens/<int:pk>/tempo/<int:entry_pk>/encerrar/",
        time_tracking_views.service_order_time_finish_view,
        name="service_order_time_finish",
    ),
    path(
        "ordens/<int:pk>/aprovar-orcamento/",
        order_views.service_order_approve_budget_view,
        name="service_order_approve_budget",
    ),
    path(
        "ordens/<int:pk>/cancelar/",
        order_views.service_order_cancel_view,
        name="service_order_cancel",
    ),
    path(
        "ordens/<int:pk>/itens/adicionar/",
        item_views.service_order_item_add_view,
        name="service_order_item_add",
    ),
    path(
        "ordens/<int:pk>/itens/<int:item_pk>/editar/",
        item_views.service_order_item_update_view,
        name="service_order_item_update",
    ),
    path(
        "ordens/<int:pk>/itens/<int:item_pk>/excluir/",
        item_views.service_order_item_delete_view,
        name="service_order_item_delete",
    ),
    path(
        "ordens/<int:pk>/observacoes/adicionar/",
        note_views.service_order_note_create_view,
        name="service_order_note_create",
    ),
    path(
        "ajax/veiculos-por-cliente/",
        ajax_views.vehicles_by_customer_view,
        name="vehicles_by_customer",
    ),
]
