# Generated by Django 5.2.13 on 2026-05-04 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aiprompttemplate",
            new_name="ai_aiprompt_use_cas_08be52_idx",
            old_name="ai_aiprompt_use_ca_0d8f1a_idx",
        ),
        migrations.RenameIndex(
            model_name="aiprompttemplate",
            new_name="ai_aiprompt_code_ae7258_idx",
            old_name="ai_aiprompt_code_3f9a62_idx",
        ),
        migrations.RenameIndex(
            model_name="airequest",
            new_name="ai_aireques_use_cas_1e6641_idx",
            old_name="ai_aireques_use_ca_59c0bb_idx",
        ),
        migrations.RenameIndex(
            model_name="airequest",
            new_name="ai_aireques_created_438c59_idx",
            old_name="ai_aireques_created_54fca5_idx",
        ),
        migrations.RenameIndex(
            model_name="aiusagelog",
            new_name="ai_aiusagel_feature_c389e3_idx",
            old_name="ai_aiusage_feature_41ab75_idx",
        ),
        migrations.RenameIndex(
            model_name="aiusagelog",
            new_name="ai_aiusagel_created_7d1979_idx",
            old_name="ai_aiusage_created_7bc31e_idx",
        ),
    ]
